name: austerity
description: Dart and Flutter static code analysis, but not for the faint hearted. This code tries to turn all violations in to red squiggly lines
version: 1.3.0
repository: https://github.com/MelbourneDeveloper/austerity

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
